### ISSUE TITLE
Cassandra Version Update Issue

### ISSUE THREAD

**Issue by PonMalar2703** [linux-on-ibm-z/dockerfile-examples#20]
I am updating Cassandra version (Version - 4.0.3) in the Dockerfile. 
Successfully build the docker image but facing below error while running Docker container.

WARN [main] 2022-06-17 11:47:45,443 NativeTransportService.java:165 - epoll not available
java.lang.UnsatisfiedLinkError: could not load a native library: netty_transport_native_epoll_s390_64
	at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:226)
	at io.netty.channel.epoll.Native.loadNativeLibrary(Native.java:250)
	at io.netty.channel.epoll.Native.<clinit>(Native.java:69)
	at io.netty.channel.epoll.Epoll.<clinit>(Epoll.java:39)
	at org.apache.cassandra.service.NativeTransportService.useEpoll(NativeTransportService.java:164)
	at org.apache.cassandra.net.SocketFactory$Provider.optimalProvider(SocketFactory.java:163)
	at org.apache.cassandra.net.SocketFactory.<init>(SocketFactory.java:184)
	at org.apache.cassandra.net.MessagingService.<init>(MessagingService.java:234)
	at org.apache.cassandra.net.MessagingService$MSHandle.<clinit>(MessagingService.java:226)
	at org.apache.cassandra.net.MessagingService.instance(MessagingService.java:231)
	at org.apache.cassandra.service.StorageService.prepareToJoin(StorageService.java:906)
	at org.apache.cassandra.service.StorageService.initServer(StorageService.java:785)
	at org.apache.cassandra.service.StorageService.initServer(StorageService.java:730)
	at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:420)
	at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:765)
	at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:889)
	Suppressed: java.lang.UnsatisfiedLinkError: could not load a native library: netty_transport_native_epoll
		at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:226)
		at io.netty.channel.epoll.Native.loadNativeLibrary(Native.java:253)
		... 14 common frames omitted
	Caused by: java.io.FileNotFoundException: META-INF/native/libnetty_transport_native_epoll.so
		at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:175)
		... 15 common frames omitted
		Suppressed: java.lang.UnsatisfiedLinkError: no netty_transport_native_epoll in java.library.path
			at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1860)
			at java.lang.Runtime.loadLibrary0(Runtime.java:871)
			at java.lang.System.loadLibrary(System.java:1124)
			at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
			at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:351)
			at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:136)
			... 15 common frames omitted
			Suppressed: java.lang.UnsatisfiedLinkError: no netty_transport_native_epoll in java.library.path
				at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1860)
				at java.lang.Runtime.loadLibrary0(Runtime.java:871)
				at java.lang.System.loadLibrary(System.java:1124)
				at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
				at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
				at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
				at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
				at java.lang.reflect.Method.invoke(Method.java:498)
				at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:385)
				at java.security.AccessController.doPrivileged(Native Method)
				at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:377)
				at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:341)
				... 16 common frames omitted
Caused by: java.io.FileNotFoundException: META-INF/native/libnetty_transport_native_epoll_s390_64.so
	at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:175)
	... 15 common frames omitted
	Suppressed: java.lang.UnsatisfiedLinkError: no netty_transport_native_epoll_s390_64 in java.library.path
		at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1860)
		at java.lang.Runtime.loadLibrary0(Runtime.java:871)
		at java.lang.System.loadLibrary(System.java:1124)
		at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
		at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:351)
		at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:136)
		... 15 common frames omitted
		Suppressed: java.lang.UnsatisfiedLinkError: no netty_transport_native_epoll_s390_64 in java.library.path
			at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1860)
			at java.lang.Runtime.loadLibrary0(Runtime.java:871)
			at java.lang.System.loadLibrary(System.java:1124)
			at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
			at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
			at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
			at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
			at java.lang.reflect.Method.invoke(Method.java:498)
			at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:385)
			at java.security.AccessController.doPrivileged(Native Method)
			at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:377)
			at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:341)
			... 16 common frames omitted

**Comment by vibhutisawant** [comment]
Our published Dockerfile version is v3.11.10 and it works as expected. We cannot assure that v3.11.10 Dockerfile will work correctly for newer releases. We currently don't know exactly when we'll be doing our next publish yet.
